/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Playground: typeof import('./.vitepress/components/Playground.vue')['default']
    ShikijiPlayground: typeof import('./.vitepress/components/ShikijiPlayground.vue')['default']
  }
}
